version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    BUILD_ENV: "prod"
  secrets-manager:
    DOCKERHUB_PASS: "dockerhub/credentials:/dockerhub/credentials-password"
    DOCKERHUB_USERNAME: "dockerhub/credentials:/dockerhub/credentials-username"
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
      - ng add @angular/material
      - echo $DOCKERHUB_USERNAME
      - echo $DOCKERHUB_PASS
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration=production --output-path dist
      - cd dist
      - docker build -t coordgrabber .
      - docker tag coordgrabber coordgrabber:latest
      - docker push $DOCKERHUB_USERNAME/coordgrabber:latest

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes