AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CoordGrabberDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: Fn::ImportValue: production:ExternalUrl
          Id: CoordGrabberAlbUrl
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: https-only
        Enabled: 'true'
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: 'false'
          Bucket: coord-grabber.logging.s3.amazonaws.com
          Prefix: logs
        Aliases:
        - cdbsandbox.com
        - '*.cdbsandbox.com'
#        - coordgrabber.com
#        - '*.coordgrabber.com'
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: CoordGrabberAlbUrl
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
#          TrustedSigners:
#          - 1234567890EX
#          - 1234567891EX
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:057147015553:certificate/d8344d6c-3e18-49e3-b12d-e55d87c59c17
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only